### ISSUE TITLE
Consistency in names of cited authors / sortname / authauthor

### ISSUE THREAD

**Issue by guyemerson** [langsci/hpsg-handbook#11]
I noticed that in the references for our chapter (computational linguistics), Flickinger (2017) appears before Flickinger (1987).  It seems that this is because one reference is with a middle initial and the other without.  There are also citations of Flickinger with different first names (Dan or Daniel).  I wasn't sure which one should be considered correct.  More generally, I thought it might be worth raising this point, as this could affect citations of other authors, and it could be worth checking this in the final proof-reading pass.

**Comment by stefan11** [comment]
Yes, thanks. The trick is to add sortname fields that are conventionalized. The bibtex entry is supposed to contain the names that are on the publication. For the index we need authautor and autheditor fields filled in. If you want you can do this, otherwise we will take care of this in the end.

**Comment by guyemerson** [comment]
I didn't know about the sortname and authauthor fields -- it seems Biber expanded Bibtex more than I realised!  If you will take care of this, that will be great, thank you!

**Comment by stefan11** [comment]
sortname is standard, authauthor is added by us. biber/biblatex is a huge step forward in comparison to what we had before.
