### ISSUE TITLE
alignment of examples in relative-clause.tex

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#12]
![Bildschirmfoto 2020-02-21 um 15 22 38](https://user-images.githubusercontent.com/4655859/75042220-5c765600-54be-11ea-83a3-d1c450487b21.png)

The examples in relative-clause.tex are not aligned. This can be done with \ex[]{ ... } and \ex[*]{ ... } respectively. 

Example:
\eal
\ex[*]{\label{x:rc-29}
I wonder [some pictures of whom] they were admiring.  
}
\ex[]{\label{x:rc-30} 
the children [some pictures of whom] they were admiring
}
\zl

**Comment by kalvelal** [comment]
fixed #12

**Comment by stefan11** [comment]
Please only do this for examples having ungrammatical examples in the listing. I fixed this.
