### ISSUE TITLE
Distance between several \eal's is too big

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#14]
![Bildschirmfoto 2020-03-29 um 14 20 20](https://user-images.githubusercontent.com/4655859/77848953-747d7b80-71c8-11ea-8050-b80bf1c60621.png)

**Comment by kopeckyf** [comment]
Can you post the code that generates the output, please?

**Comment by stefan11** [comment]
```latex

\eal
\ex The White House is very careful about this. An official representative [[will
              personally read each document] and [reply to every letter]].\\
              ($\forall$ doc-letter $>$$\exists$ representative / $\exists$ representative $>$$\forall$ doc-letter)

\ex We had to do this ourselves. By the end of the year,
some student [[had proof-read every document] and [corrected each
theorem]].\\
($\forall$  doc-theorem $>$$\exists$ student / $\exists$ student $>$$\forall$ doc-theorem)

\ex Your task is  to document the social interaction
between [[each female] and [an adult male]].\\
($\forall$ female $>$$\exists$ adult male / $\exists$ adult male $>$$\forall$ female)
\zllast
}

```
 

\eal
\label{cc2}
\ex[*]{Which celebrity did you see [Priscilla and a picture of \spc]?\\
(cf.\ with `Did you see Priscilla and a picture of Elvis?')}
\ex[*]{Which celebrity did you see [a picture of \spc and Priscilla]?\\
(cf.\ with `Did you see a picture of Elvis and Priscilla?')}
\zl

\eal 
\label{cc3} 
\ex Which celebrity did you see [the brother of \spc with Priscilla]?
\ex Which celebrity did you see [Priscilla with the brother of \spc]?
\zl

\eal \label{compar} 
\ex Which celebrity did  [[you enjoy the memoir of \spcs more] than
                                 [any other non-fiction book]]?

\ex Which celebrity did you say that [[the sooner we take a picture of \spc ],
[the quicker we can go home]]?
\zl

**Comment by kopeckyf** [comment]
The problem is that `\eal`...`\zl` are designed to be surrounded by main text, not by other examples. 

I don't see any benefits of using `\eal` at all, since the only thing it adds is a `\raggedright` which could be achieved differently, and this makes a difference only very rarely. 

Here's the workaround for `\eal`:
```
\eal
\label{cc2}
\ex[*]{Which celebrity did you see [Priscilla and a picture of \spc]?\\
(cf.\ with `Did you see Priscilla and a picture of Elvis?')}
\ex[*]{Which celebrity did you see [a picture of \spc and Priscilla]?\\
(cf.\ with `Did you see a picture of Elvis and Priscilla?')}
\z

\ex
\label{cc3}
\begin{xlist} 
\ex Which celebrity did you see [the brother of \spc with Priscilla]?
\ex Which celebrity did you see [Priscilla with the brother of \spc]?
\z

\ex
\label{compar} 
\begin{xlist}
\ex Which celebrity did  [[you enjoy the memoir of \spcs more] than
                                 [any other non-fiction book]]?

\ex Which celebrity did you say that [[the sooner we take a picture of \spc ],
[the quicker we can go home]]?
\zl
```

**Comment by stefan11** [comment]
But this is a lot of clutter and does not make sense semantically. I would really not like this to be in the text. You will never be able to explain this to authors.

\eal is a shortcut for saying "a list of examples starts" and \zl is a shortcut for saying "a list of examples ends here". \eal and \zl were in gb4e right from the beginning.

Maybe we should have \zlcont and \ealcont as variants for multiple collections of items. So we would get:

```latex
\eal
\label{cc2}
\ex[*]{Which celebrity did you see [Priscilla and a picture of \spc]?\\
(cf.\ with `Did you see Priscilla and a picture of Elvis?')}
\ex[*]{Which celebrity did you see [a picture of \spc and Priscilla]?\\
(cf.\ with `Did you see a picture of Elvis and Priscilla?')}
\zlcont

\ealcont
\label{cc3}
\ex Which celebrity did you see [the brother of \spc with Priscilla]?
\ex Which celebrity did you see [Priscilla with the brother of \spc]?
\zlcont

\ealcont
\label{compar} 
\ex Which celebrity did  [[you enjoy the memoir of \spcs more] than
                                 [any other non-fiction book]]?

\ex Which celebrity did you say that [[the sooner we take a picture of \spc ],
[the quicker we can go home]]?
\zl
```

**Comment by kopeckyf** [comment]
I agree, but the problem is entirely with using the undocumented shortcuts `\ea`, `\eal`, etc. The "official" way in `gb4e` would be 

```
\begin{exe}
\ex
\begin{xlist}
\ex
\ex
\end{xlist}

\ex
\begin{xlist}
\ex
\ex
\end{xlist}
\end{exe}
```

**Comment by stefan11** [comment]
Everybody uses this. The notational clutter with begin and end is unacceptable. One breaks their fingers writing all this. I teach people to use the shortcuts since without them it is not clear what people do there. I had the shortcuts in tex tutorials and everywhere and I hope you will cover this in the tex for linguists books as well.

**Comment by kopeckyf** [comment]
I understand completely. For us to cover that in the LaTeX intro book, there would need to be some stable code base. So we would need to improve the gb4e code first - I actually thought about this, but there is not enough time right now. 

Taking into account that `expex` actually performs really well in this respect (in others, too), has an even simpler syntax, I'd personally prefer we phase out `gb4e` soon and move to `expex` rather than reinventing the wheel.

**Comment by stefan11** [comment]
This was the package Jean-Pierre Koenig suggested?

**Comment by kopeckyf** [comment]
Yes. You can have a look here: [expex documentation on CTAN](http://mirrors.ctan.org/macros/generic/expex/expex-doc.pdf)
