### ISSUE TITLE
forest figure causes a Dimension too large error (minimalism.tex)

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#22]
! Dimension too large.
<recently read> \pgf@x
                      
l.1099 }

```latex
\begin{forest}
for tree={nice empty nodes,% every conditional anchor=north adapts the
specific node to this setting.
                            if n children={3}{for children={
                                anchor=north,
                                if n=1{inner sep=0pt,child anchor=north
east,edge=-{Triangle[]}}{
                                if n=3{inner sep=0pt,child anchor=north
west,edge=-{Triangle[]}}{}}}
                            }{
                                if n children={2}{for children={
                                anchor=north,
                                if n=1{child anchor=north
east,edge=-{Triangle[]}}{
                                if n=2{child anchor=north
west,edge=-{Triangle[]}}{}}}
                                }{}
                            },
                            },
                    delay={where content={...}{for parent={for
children={anchor=north}}}{}},
                   
transfer/.style={yshift=5mm,tikz={\node[gray,right=3cm of .east]
(stefanstransfer) {Transfer};\path[{Latex[]}-,gray] (.east) edge[]
(stefanstransfer);}},
                    lexicon/.style={tikz={\node[left=1.5cm of .base
west,anchor=base] (stefanslexicon) {\strut lexicon};\path[-{Latex[]}]
(stefanslexicon) edge (.west);}}
[numeration,lexicon[,transfer
    [PHON][,transfer
        [PHON][,transfer
            [PHON,baseline][,transfer
                [PHON][...[,transfer
                        [PHON][SEM]
                        ]
                    ][SEM]]
            [SEM]]
        [SEM]]
    [SEM]]
]
\end{forest}
```

**Comment by sasozivanovic** [comment]
I could not reproduce the error, but I guess it was due to `nice empty nodes`, a style which is not so nice sometimes. I have manually used `calign=fixed edge angles` on the "transfer" nodes, this might help.

And then I play with the tree a bit ;-)  First, to showcase dynamic node creation. Second, to put the two subfigures side-by-side without shrinking them. Third, to make the vertical segments of the tree of equal sizes. I hope that's all ok ...

Commit 6b0c0b3d035ed3f095527760cd36b0af0299a7d3

**Comment by stefan11** [comment]
Thanks this works now, but a part from "lexicon -> numeration" is gone. 
![Bildschirmfoto 2020-05-03 um 15 18 44](https://user-images.githubusercontent.com/4655859/80915261-6257a580-8d51-11ea-8d47-13f8dff53434.png)


Could you please merge your commits to the main trunk? Otherwise I miss them sometimes.

**Comment by sasozivanovic** [comment]
Yes, overlays are not externalized correctly. I'll redo the tree in another way.

Sure, I just thought you might want to be the master of master ;-)
