### ISSUE TITLE
externalization of first image in dg.tex fails

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#23]
Externalizing two tikz figures mixes them up. It should look like this:
![Bildschirmfoto 2020-05-02 um 17 58 30](https://user-images.githubusercontent.com/4655859/80869077-8b6b2e00-8c9e-11ea-9228-cafaa4432c30.png)

But the result is this:
![Bildschirmfoto 2020-05-02 um 17 55 11](https://user-images.githubusercontent.com/4655859/80869002-1992e480-8c9e-11ea-859c-6853d12d2680.png)

Blocking the first from externalization does the trick.

```latex
\begin{figure}
	\centering
%	
{
% If I externalieze this one it gives me a wrong picture.
\tikzexternaldisable
\TZbox{%
\TZbox{%
       \TZbox{many} 
       \TZbox{students}}
\TZbox{%
       \TZbox{enjoy}
       \TZbox{syntax}}}
}

\begin{tikzpicture}[node distance=.2cm]
\node[draw](many) at (0,0){\strut{many}};
\node[draw](students) [right=of many]{\strut students};
\node[draw](enjoy) [right=of students]{\strut enjoy};
\node[draw](syntax) [right= of enjoy]{\strut syntax};
\draw[->] (enjoy)[out=north,in=north] to (syntax);
\draw[->] (enjoy)[out=north,in=north] to (students);
\draw[->] ([xshift=-.2cm]students.north)[out=north,in=north] to (many);
\end{tikzpicture}
%
	\caption{Phrase structure and dependency structure contrasted}
	\label{fig:1}
\end{figure}
```

**Comment by sasozivanovic** [comment]
`\TZbox` is a TikZ picture, but these may not be nested (even in a "normal" situation, let alone with externalization). In https://github.com/langsci/hpsg-handbook/commit/2139154ae933db54ef8af8f35c5d8e7a7917f17f, I rewrote the picture and deleted the `\TZbox` command.

**Comment by stefan11** [comment]
Thanks! I got this from stackexchange ...
