### ISSUE TITLE
! You can't use `\lower' in vertical mode.

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#27]
[6]
! You can't use `\lower' in vertical mode.
\box_move_down:nn langsci/langsci-avm#1#2->\tex_lower:D 
                                     \__box_dim_eval:n {#1}#2
l.437                          arg1 & \1 ] \} ] ]}
                                                  
? 

The current style file fails on
```latex
\avm{
[ cat|head & [\type*{adv}
               mod & !\upshape VP[\type{nonfin}]!:\1 ]\\
  cont     & [ restr \{ [ pred & neg-rel\\
                         arg1 & \1 ] \} ] ]}
```

(HPSG handbook, negation.tex)

**Comment by kopeckyf** [comment]
Output in vanilla `langsci-avm`:

![box-move-down-bug](https://user-images.githubusercontent.com/10461729/84510068-f0b23600-acc4-11ea-867d-d5055fdc15a9.png)

**Comment by stefan11** [comment]
Sorry. Messed this up.
