### ISSUE TITLE
The crossreferencing with hyperref does not work

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#4]
For example from idiom.tex

> Both Kay et al. (2015) and Bargmann & Sailer (2018) attempt to derive the (par- tial) syntactic inflexibility of non-decomposable idioms from independent prop- erties of the relevant constructions. As such, they subscribe to the programmatic statement of Nunberg et al. (1994) from (3) above. In this respect, the extension of the lexical approach from decomposable idioms to all syntactically regular expressions has been a clear step forward.

(3) is the correct referecne but when clicking the link, one gets to the beginning of the chapter not to (3).

**Comment by guyemerson** [comment]
I think this problem is specifically for cross-references using langsci-gb4e?

**Comment by kopeckyf** [comment]
@guyemerson Unfortunately this error also occurs with hyperrefs to Footnotes and Sections.

**Comment by kopeckyf** [comment]
The error is possibly related to some of the code loaded in localpackages.tex. After commenting out some packages, the behaviour changes back to normal. However, packages from CTAN / the LangSci styles are fine.

Please check the material you contributed manually for any interference with hyperref.

**Comment by stefan11** [comment]
=:-( Thanks! Do you have more specific suggestions as for which packages are concerned?

**Comment by stefan11** [comment]
Duplicate of #8
