### ISSUE TITLE
Unicode problem in understudied-languages.bib

### ISSUE THREAD

**Issue by stefan11** [langsci/hpsg-handbook#7]
Mulder, Jean Gail. 1994. Ergativity in Coast Tsimshian (Sm’algy￿̲x). Berkeley: Uni- versity of California Press.

There is an underlined a that does not come out as unicode.

@book{mulder94,
	Address = {Berkeley},
	Author = {Jean Gail {Mulder}},
	Date-Added = {2019-06-25 23:33:03 -0500},
	Date-Modified = {2019-06-25 23:33:03 -0500},
	Publisher = {University of California Press},
	Title = {Ergativity in {C}oast {T}simshian ({S}m'algy𝚊̲x)},
	Year = {1994}}

**Comment by kopeckyf** [comment]
This glyph is not available in the font Libertine, which is still in use in your book project. If you import the current class version from our langscibook repository, the switch to Libertinus should resolve the issue. The current Libertinus font has this font available. 

There are two ways to print this glyph. One is "Latin lower a with macron below", the other "Latin lower a with line below".

Please note that I'm planning a push to Libertinus in mid-January to add missing glyphs and correct diacritics placement. If you find any further issues with the Libertinus font, could you open an issue in the langsci/langsci-libertinus repository?
